CHANNEL_DB = {
    "거침없는 경제학": {
        "host": "Tae-oh",
        "host_desc": "레드 복면, 블랙 슈트",
        "color_primary": "#FF6B6B",
        "color_secondary": "#1A1A1A",
        "tone": "독설가 (공격적 팩트 폭격)",
        "target": "돈을 잃고 분노하는 투자자",
        "seo_keywords": ["경제위기", "하락장", "폭락", "경고", "자산방어"],
        "thumbnail_style": "시청자의 공포와 분노를 자극하는 강렬한 수치와 붉은색 강조",
        "community_tone": "강한 경고: 아직도 위기를 모르는 분들에게 이 영상을 공유하세요.",
        "community_quiz": "다음 중 가장 먼저 터질 경제 폭탄은?",
        "visual_mood": "공포, 분노, 붉은 경고, 날카로운 수치 충돌"
    },
    "머니매커니즘": {
        "host": "Gear Yoon",
        "host_desc": "금테 안경, 에메랄드 눈빛",
        "color_primary": "#5BC8A0",
        "color_secondary": "#FFE97A",
        "tone": "설계자 (냉철한 시스템 분석)",
        "target": "구조를 이해하고 싶은 전략가",
        "seo_keywords": ["자본주의", "금융구조", "시스템", "투자전략"],
        "thumbnail_style": "자본의 흐름과 시스템의 톱니바퀴 구조를 정교하게 시각화",
        "community_tone": "냉철한 분석: 시스템의 허점을 알면 기회가 보입니다. 구조를 이해하셨나요?",
        "community_quiz": "이 시스템에서 가장 중요한 설계 변수는?",
        "visual_mood": "시스템 구조, 톱니바퀴, 자본 흐름의 설계도"
    },
    "친절한 경제학자": {
        "host": "Saito",
        "host_desc": "단정하게 넘긴 흑발, 세련된 뿔테",
        "color_primary": "#2C3E50",
        "color_secondary": "#F1C40F",
        "tone": "현대적 멘토 (지식 큐레이터)",
        "target": "글로벌 경제 흐름이 궁금한 대중",
        "seo_keywords": ["글로벌경제", "환율", "금리전망", "통찰"],
        "thumbnail_style": "세련된 글로벌 마켓 그래프와 태블릿을 든 스마트한 이미지",
        "community_tone": "지적인 멘토: 복잡한 경제 흐름 속에서 우리가 붙잡아야 할 본질은 이것입니다.",
        "community_quiz": "현재 글로벌 시장에서 가장 주목해야 할 지표는?",
        "visual_mood": "글로벌 그래프, 세련된 디지털 분석 공간"
    },
    "남몰래 경제학": {
        "host": "Shadow",
        "host_desc": "보라 복면, 거대 돋보기",
        "color_primary": "#9B72CF",
        "color_secondary": "#E0E0E0",
        "tone": "정보원 (은밀한 폭로)",
        "target": "숨겨진 진실을 알고 싶은 사람",
        "seo_keywords": ["유통비밀", "가격담합", "폭로", "내부고발"],
        "thumbnail_style": "어두운 배경에서 돋보기가 특정 비밀을 비추는 미스테리 연출",
        "community_tone": "은밀한 폭로: 아무도 말하지 않는 진실, 여러분은 이미 알고 계셨나요?",
        "community_quiz": "다음 중 가장 심각하다고 생각하는 거품은?",
        "visual_mood": "미스터리, 은밀한 폭로, 숨겨진 진실 추적"
    },
    "사이언스로그": {
        "host": "Log",
        "host_desc": "블루 바이저, 하이테크 슈트",
        "color_primary": "#7DD8F5",
        "color_secondary": "#F0FBFF",
        "tone": "기록관 (논리적 데이터 분석)",
        "target": "과학적 근거를 찾는 이성주의자",
        "seo_keywords": ["AI", "뇌과학", "데이터분석", "물리학", "우주"],
        "thumbnail_style": "차가운 사이버 공간과 데이터를 홀로그램으로 분석하는 연출",
        "community_tone": "객관적 기록: 데이터는 거짓말을 하지 않습니다. 기록된 사실을 확인하세요.",
        "community_quiz": "최근 발표된 데이터 중 가장 놀라운 수치는?",
        "visual_mood": "차가운 데이터, 실험실, 홀로그램 분석"
    },
    "사이언스툰": {
        "host": "Nutty",
        "host_desc": "대형 고글, 익살스러운 표정",
        "color_primary": "#85D98A",
        "color_secondary": "#FFFDE7",
        "tone": "발명가 (유쾌한 발견)",
        "target": "과학을 재미있게 배우려는 대중",
        "seo_keywords": ["신기한실험", "과학원리", "상식", "초등과학"],
        "thumbnail_style": "과장된 표정과 팝아트 스타일의 스피드 라인, 튀어오르는 액체",
        "community_tone": "유쾌한 발견: 와! 실험 결과가 예상과 다른데 여러분은 어떠셨나요?",
        "community_quiz": "다음 중 실제로 가능한 실험은 무엇일까요?",
        "visual_mood": "팝아트, 유쾌한 과장, 빠른 에너지"
    },
    "미래인사이트": {
        "host": "Future",
        "host_desc": "사이버네틱 안구, 네온 재킷",
        "color_primary": "#9B8FC8",
        "color_secondary": "#E8F4FD",
        "tone": "선구자 (미래 예측)",
        "target": "변화를 먼저 알고 싶은 얼리어답터",
        "seo_keywords": ["2030", "미래직업", "로봇", "자율주행", "트렌드"],
        "thumbnail_style": "사이버펑크 톤의 네온 불빛과 홀로그램 디스플레이",
        "community_tone": "선구자적 제안: 미래는 준비된 자의 것입니다. 변화를 맞이할 준비가 되셨나요?",
        "community_quiz": "10년 후 우리 삶을 가장 크게 바꿀 기술은?",
        "visual_mood": "사이버펑크, 예측, 미래 경고"
    },
    "히스토리프로파일러": {
        "host": "Lupus",
        "host_desc": "브라운 페도라, 트렌치코트",
        "color_primary": "#C4A882",
        "color_secondary": "#FDF5E6",
        "tone": "탐정 (노아르풍 수사)",
        "target": "역사 미스터리를 좋아하는 팬",
        "seo_keywords": ["역사미스터리", "미제사건", "프로파일링"],
        "thumbnail_style": "세피아 톤의 어두운 분위기와 붉은 실로 연결된 단서 보드",
        "community_tone": "탐정의 추리: 모든 단서는 현장에 있었습니다. 범인은 과연 누구일까요?",
        "community_quiz": "제시된 단서 중 가장 결정적인 증거는?",
        "visual_mood": "세피아, 단서 보드, 역사 추적"
    },
    "친절한 심리학자": {
        "host": "Psy",
        "host_desc": "깔끔한 민트 맨투맨, 반무테 안경",
        "color_primary": "#3EB489",
        "color_secondary": "#E2725B",
        "tone": "마음 설계자 (명쾌한 심리 분석)",
        "target": "감정 구조를 이해하고 싶은 청년층",
        "seo_keywords": ["자존감", "인간관계", "마음설계", "정신건강"],
        "thumbnail_style": "민트색의 깨끗함과 심리 프리즘을 통한 감정의 분해/해석 표현",
        "community_tone": "명쾌한 해설: 당신의 마음이 어긋난 이유는 명확합니다. 함께 다시 설계해 봅시다.",
        "community_quiz": "비슷한 상황에서 당신의 마음은 어떤 신호를 보내나요?",
        "visual_mood": "감정 해석, 심리 프리즘, 깨끗한 상담형 공간"
    },
    "거리의 경제학": {
        "host": "Hyeonjang",
        "host_desc": "오렌지 비니, 장바구니",
        "color_primary": "#F5A55A",
        "color_secondary": "#FFF3E0",
        "tone": "활동가 (생생한 민생 현장)",
        "target": "실생활 경제가 궁금한 서민",
        "seo_keywords": ["물가", "장바구니", "서민경제", "최저임금"],
        "thumbnail_style": "시장의 생생한 색감과 장바구니, 실제 영수증 수치 부각",
        "community_tone": "생생한 공감: 시장에서 본 현실은 더 차가웠습니다. 여러분의 동네 물가는 어떤가요?",
        "community_quiz": "요즘 가장 체감되는 물가 상승 품목은?",
        "visual_mood": "시장 현장, 영수증, 생계감 있는 실제 공간"
    },
    "친절한 공학자": {
        "host": "Engi",
        "host_desc": "흰색 안전모, 푸른 작업복",
        "color_primary": "#4A90E2",
        "color_secondary": "#FF9F43",
        "tone": "설계자 (실용적 해결사)",
        "target": "작동 원리가 궁금한 대중",
        "seo_keywords": ["작동원리", "제품설계", "메커니즘", "기술리뷰"],
        "thumbnail_style": "푸른 도면 위에 안전모를 쓴 캐릭터와 정교한 기계 부품 묘사",
        "community_tone": "실용적 해결: 불편함을 해결하는 설계의 묘미, 이 제품의 진짜 가치를 발견하셨나요?",
        "community_quiz": "이 도구의 설계에서 가장 효율적인 부분은?",
        "visual_mood": "도면, 작동 구조, 정교한 기계 설명"
    },
    "친절한 과학자": {
        "host": "Scien",
        "host_desc": "단정한 갈색 머리, 둥근 안경",
        "color_primary": "#50C878",
        "color_secondary": "#FDFD96",
        "tone": "관찰자 (따뜻한 호기심)",
        "target": "일상 속 과학 원리가 궁금한 대중",
        "seo_keywords": ["일상과학", "과학적설계", "생명과학", "원리"],
        "thumbnail_style": "따뜻한 초록색 연구실에서 비커와 원자 기호가 어우러진 연출",
        "community_tone": "따뜻한 호기심: 우리 곁의 과학은 참 다정하죠. 일상 속의 신비함을 찾아보세요.",
        "community_quiz": "오늘 발견한 일상 속 과학 현상 중 가장 신기한 것은?",
        "visual_mood": "따뜻한 연구실, 비커, 생활 과학"
    },
    "친절한 사회학자": {
        "host": "Socio",
        "host_desc": "둥근 안경, 브라운 가디건",
        "color_primary": "#D2B48C",
        "color_secondary": "#4E342E",
        "tone": "관찰자 (인간적인 통찰)",
        "target": "사회 현상의 이유가 궁금한 대중",
        "seo_keywords": ["사회현상", "인간관계", "공동체", "사회구조"],
        "thumbnail_style": "따뜻한 베이지 톤 배경과 사람들 사이의 연결 고리(네트워크) 시각화",
        "community_tone": "인간적 통찰: 우리가 맺는 관계의 이면에는 사회라는 설계도가 숨어 있습니다.",
        "community_quiz": "우리 사회의 연결 고리 중 시급히 복구해야 할 것은?",
        "visual_mood": "관계망, 사회 구조, 사람 사이의 거리와 연결"
    }
}
